[package]
name = "hello_world_rocket"
version = "0.1.0"
authors = ["Ole Martin Ruud <barskern@outlook.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.1.0"
rocket = "0.3.16"
rocket_codegen = "0.3.16"
